djangoProject12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('website.urls'), name="index"),
    path('website', include('website.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = "website"


urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name ="about"),
    path("rate",views.rate, name="rate"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("profile", views.profpage, name="profpage"),
    path("contact", views.contact, name="contact"),
    path("searched", views.search, name="search")
]

website/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Currency(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    date_achieved = models.DateField(null=True)
    description = models.TextField(null=True)
    avatar = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.name}"





class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(User, max_length=150)
    email = models.CharField(User, max_length=100)
    currencies = models.ManyToManyField(Currency)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return f'{self.user.username} Profile'

website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('currencies',)
        exclude = ()

website/views.py
import requests
from django.contrib.auth import login
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .models import Currency
from .forms import NewUserForm, UserForm, ProfileForm
from django.contrib import messages
from django.template import loader
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView


# Create your views here.


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def rate(request):
    return render(request, 'rate.html', {

        "v_currencies": Currency.objects.all()
    })


def search(request):
    if request.method == "POST":
        searched = request.POST["q"]  # sometimes need parentheis
        smatch = Currency.objects.filter(
            description__contains=searched) | Currency.objects.filter(
                name__contains=searched)
        return render(request, "search_results.html", {
            "searched": searched,
            "schedules": smatch
        })
    else:
        return render(request, "search_results.html", {})


def contact(request):
    return render(request, "contact.html")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("website:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("website:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("website:index")


def profpage(request):
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile was successfully updated!')
        elif profile_form.is_valid():
            profile_form.save()
        else:
            messages.error(request, 'Unable to complete request')
        return redirect("website:profpage")
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request=request, template_name="profile.html", context={"user": request.user,
                                                                          "user_form": user_form,
                                                                          "profile_form": profile_form})

templates/about.html
{% extends "layout.html" %}
{% load static %}

{% block body %}

    <!-- about -->
    <section id="about" class="pt-4">
        <h1 class="display-4 text-center my-5 text-white">About Crypto Pal</h1>
        <div class="row ">
            <div class="col-lg order-lg-2 bg-dark text-white">
                <h3 class="mb-4">Location</h3>
                <img class="mb-4 img-fluid rounded d-none d-sm-block" src="{% static 'website/img/greece.jpg' %}"
                     alt="Portland">
                <p>Our base is located in beautiful Greece, but with worldwide goals.</p>
                <p>Discover new features of securely monitoring your crypto wallet.</p>
            </div>
            <div class="col-lg order-lg-1 text-white">
                <h3 class="mb-4 text-white">About</h3>
                <p>Welcome to an ever-striving community of traders and pioneers in the world of cryptocurrencies.</p>
                <p>Our goal is to gather statistics for user's most favorite cryptocurrencies,<br>
                    along with details on the purchases they have made in order to determine future markets.</p>
                <p>We gather anonymous information regarding traders and their markets tendencies,<br>
                    to establish a more satisfactory and futuristic way of determining markets.</p>
            </div>
            <div class="col-lg order-3 bg-dark">
                <h3 class="mb-4 text-white">Live Prices</h3>
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action"><strong>Bitcoin</strong>:<p
                            class="card-header" id="txtBitcoin">PRICE</p></a>
                    <a href="#" class="list-group-item list-group-item-action"><strong>Ethereum</strong>:<p
                            class="card-header" id="txtEthereum">PRICE</p></a>
                    <a href="#" class="list-group-item list-group-item-action"><strong>Litecoin</strong>:<p
                            class="card-header" id="txtLitecoin">PRICE</p></a>
                    <a href="#" class="list-group-item list-group-item-action"><strong>XRP</strong>:<p
                            class="card-header" id="txtRipple">PRICE</p></a>
                    <a href="#" class="list-group-item list-group-item-action"><strong>BNB</strong>:<p
                            class="card-header" id="txtBnb">PRICE</p></a>
                    <a href="#" class="list-group-item list-group-item-action"><strong>Tether</strong>:<p
                            class="card-header" id="txtTether">PRICE</p></a>

                </div>
            </div>
        </div>
    </section>
    <!-- /about -->
    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=EUR', function (data) {
                let btcInEur = data.EUR;
                document.getElementById("txtBitcoin").innerText = `${btcInEur} €`;
            });
        });
    </script>

    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=EUR', function (data) {
                let ethInEur = data.EUR;
                document.getElementById("txtEthereum").innerText = `${ethInEur} €`;
            });
        });
    </script>

    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=LTC&tsyms=EUR', function (data) {
                let ltcInEur = data.EUR;
                document.getElementById("txtLitecoin").innerText = `${ltcInEur} €`;
            });
        });
    </script>
    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=USDT&tsyms=EUR', function (data) {
                let usdtInEur = data.EUR;
                document.getElementById("txtTether").innerText = `${usdtInEur} €`;
            });
        });
    </script>
    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=BNB&tsyms=EUR', function (data) {
                let bnbInEur = data.EUR;
                document.getElementById("txtBnb").innerText = `${bnbInEur} €`;
            });
        });
    </script>
    <script>
        $(window).on('load', function () {
            $.getJSON('https://min-api.cryptocompare.com/data/price?fsym=XRP&tsyms=EUR', function (data) {
                let xrpInEur = data.EUR;
                document.getElementById("txtRipple").innerText = `${xrpInEur} €`;
            });
        });
    </script>

{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
    {% if  user.is_authenticated %}



        <div class="jumbotron jumbotron-fluid bg-dark text-white ">
            <div class="container text-sm-center pt-5">
                <h1 class="display-2">Welcome {{ user.username }}</h1>
                <h3><a href="{% url 'website:rate' %}">Rate your favorite crypto safely!</a></h3>
                <br>
                <div>
                    <a href="">
                        <img src="{% static 'website/img/logo.png' %}" alt="Image">
                    </a>
                </div>
                <br>

                <div class="btn-group mt-4" role="group" aria-label="Callout buttons">
                    <button type="button" class=" btn-primary btn-lg"><a class="text-white"
                                                                         href="https://www.facebook.com/">Rate us on
                        Facebook
                    </a>
                    </button>
                </div>
            </div>
        </div>
    {% else %}
        <div class="jumbotron jumbotron-fluid bg-dark text-white ">
            <div class="container text-sm-center pt-5">
                <h1 class="display-2">Crypto Pal</h1>
                <p class="lead">Welcome and don't forget to sign up!</p>
                <br>
                <div>
                    <a href="">
                        <img src="{% static 'website/img/logo.png' %}" alt="Image">
                    </a>
                </div>
                <br>

                <div class="btn-group mt-4" role="group" aria-label="Callout buttons">
                    <button type="button" class=" btn-primary btn-lg"><a class="text-white"
                                                                         href="{% url 'website:register' %}">Register</a>
                    </button>
                </div>
            </div>
        </div>
    {% endif %}





    <hr>
    <div class="row py-4 text-muted">
        <div class="col-md col-xl-5">
            <p><strong>What are we?</strong></p>
            <p>CryptoPal is a stand-alone wallet to keep track of your stacking currencies!</p>
            <p><strong>By Stefanos David Georgiou</strong></p>
        </div>
        <div class="col-md col-xl-5 ml-auto">
            <p><strong>Goals:</strong></p>
            <div class="col-lg order-lg-2 text-white">
                <p>We are an independent team of software developers and technical analysis experts.</p>
                <p>Our goals are to expand into the cryptocurrency stage and create models that can predict future price
                    movements.</p>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Full Stack Conf</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            position: relative;
        }
    </style>
</head>

<body class="bg-dark d-flex flex-column min-vh-100" id="home" data-spy="scroll" data-target=".navbar" data-offset="100">

<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'website:index' %}">
            <img src="{% static 'website/img/logo.png' %}" alt="" width="30" height="30"
                 class="d-inline-block align-text-top">
            Crypto Pal
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link text-white" href="{% url 'website:index' %}">Home<span
                        class="sr-only">(current)</span></a>
                <a class="nav-item nav-link text-white" href="{% url 'website:contact' %}">Contact</a>
                <a class="nav-item nav-link text-white" href="{% url 'website:about' %}">About</a>
                {% if user.is_authenticated %}

                    <a class="nav-item nav-link text-white" href="{% url 'website:rate' %}">Rate</a>
                    <a class="nav-item nav-link text-white" href="{% url 'website:profpage' %}">Profile</a>

                {% endif %}

            </div>
        </div>

    </div>
{% if user.is_authenticated %}
    <form class = "d-flex" id="search" method="post" action="{% url 'website:search' %}" >
                {% csrf_token %}
                 <div class = "input-group mb-0" >
                 <button class = "btn btn-outline-secondary" id="search-bt" type="submit">Search</button >
                     <input type = "text"   id="q" name="q" class = "form-control form-control-me2" placeholder = "Search crypto"   aria-label = "search"   aria-describedby = "search-bt" ></div>
</form>
{% endif %}
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Welcome, {{ user.username }}</a>
                </li>

            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:login' %}">Login</a>
                </li>

            {% endif %}
        </ul>
    </div>

</nav>
<div class="container pt-2">

    {% block body %} {% endblock %}


</div>
<!-- footer -->

<footer class="container d-flex-inline text-center mt-auto p-5">
    <div class="row">
        <div class="col-md-5 mt-md-0 mt-3">
            <h5 class="text-uppercase text-light">Information</h5>
            <p class="text-light">A striving crypto-pal to keep track of your favorite currency.
                <br>
                <img src="{% static 'website/img/logo.png' %}" alt="" width="70" height="70"
                     class="d-inline-block align-text-top"></p>
        </div>
        <hr class="clearfix w-100 d-md-none pb-3">
        <div class="col-md-3 mb-md-0 mb-3">
            <h5 class="text-uppercase text-light">Creator:</h5>
            <h4 class="text-uppercase text-light">Stefanos David Georgiou</h4>
            <h3 class="text-light">Socials</h3>

            <ul class="list-unstyled">
                <li>
                    <a href="https://github.com/Ogstef">Github</a>
                </li>
                <li>
                    <a href="https://www.facebook.com/">Facebook</a>
                </li>
                <li>
                    <a href="https://www.youtube.com/">Youtube</a>
                </li>
                <li>
                    <a href="https://www.twitter.com/">Twitter</a>
                </li>
            </ul>
        </div>
        <div class="col-md-3 mb-md-0 mb-3">
            <h5 class="text-uppercase text-light">Credentials:</h5>
            <h3 class="text-light">Experience</h3>

            <ul class="list-unstyled">
                <li>
                    <a href="https://www.acg.edu/">Education</a>
                </li>
                <li>
                    <a href="https://www.codeacademy.com/">CodeAcademy Certification</a>
                </li>
            </ul>
        </div>
    </div>
</footer>
<div class="footer-copyright text-center py-3 text-light">© 2022 Copyright:
    <p style="text-align:center" class="text-light"> CryptoPal.com </p>
</div>
<!-- /.container -->

<!--=====================================
    FORM MODAL
   =====================================-->


<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>


</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_filters %}

{% block body %}

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5 text-white">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'website:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

templates/rate.html
{% extends "layout.html" %}
{% load static %}

{% block body %}



    <section id="cryptos" class="pt-4 bg-dark">
        <h1 class="display-4 text-center my-5 text-muted">Cryptocurrencies</h1>
        <div class="row">
            {% for currency in v_currencies %}
                <div class="col-md-6 col-lg-4">
                    <div class="card mb-3 bg-dark text-white">
                        <img class="card-img-top bg-white " height="150" width="70" src="/static/website/img/{{ currency.avatar }}" alt="Vivianne">
                        <div class="card-body">
                            <h4 class="card-title">{{ currency.name }} <p><br> All time high: {{ currency.price }} $</p> </h4>
                            <p class="card-text"> {{ currency.description }} </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>



{% endblock %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_filters %}

{% block body %}

    {% load crispy_forms_tags %}

    <!--Register-->
    <section>
        <div class="container py-5 bg-dark text-white">
            <h1>Register for CryptoPal!</h1>
            <form method="POST">
                {% csrf_token %}
                {{ register_form|crispy }}
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
            <p class="text-center">If you already have an account, <a href="{% url 'website:login' %}">login</a> instead.</p>
        </div>
    </section>

{% endblock %}